### ISSUE TITLE
Pls rename the files name to English!

### ISSUE THREAD

**Issue by Handsome1080P** [badafans/better-cloudflare-ip#133]
Pls rename the files name of release to English!

**Comment by badafans** [comment]
不考虑英文用户，真正的英文用户也不需要这玩意

**Comment by hoseinnikkhah** [comment]
@badafans 
Hi, as you may know Iran has exactly same censorship of China referred as great fire wall. although this issue was created for an English translation, most of Iranians use English documents and programs. I would like to help in both Persian and English translation of this if possible.

你好，你可能知道伊朗对中国有完全相同的审查制度，称为长城防火墙。 虽然这个问题是为英文翻译而创建的，但大多数伊朗人使用英文文档和程序。 如果可能的话，我想帮忙翻译波斯语和英语。

Google translated

**Comment by badafans** [comment]
fork and translate
